#!/usr/bin/env zsh
script_dir="$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
(cd "${script_dir}" && /opt/homebrew/bin/pipenv install && /opt/homebrew/bin/pipenv run python "${script_dir}"/lib_search.py "$@")
